### ISSUE TITLE
"Parameter 'dependency' must be a Dependency" when using with webpack-dev-server

### ISSUE THREAD

**Issue by tel** [webpack/extract-text-webpack-plugin#132]
I currently have ExtractTextPlugin configured a bit like so

```
            {
                 test: /\.scss$/,
                 loader:
                     ExtractTextPlugin.extract(["css?sourceMap", "sass?sourceMap"])
             }
```

and 

```
plugins: [
         new ExtractTextPlugin("styles.css"),
]
```

When I run `webpack` this works great, but when I run `webpack-dev-server` it fails catastrophically

```
ERROR in ./app/styles/main.scss
Module build failed: Error: Parameter 'dependency' must be a Dependency
    at Tapable.process [as _addModuleChain] (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:337:9)
    at Tapable.process [as addEntry] (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:412:7)
    at SingleEntryPlugin.<anonymous> (/Users/tel/tmp/brunchex/node_modules/webpack/lib/SingleEntryPlugin.js:22:15)
    at Tapable.applyPluginsParallel (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/tapable/lib/Tapable.js:111:14)
    at Tapable.Compiler.compile (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compiler.js:391:7)
    at Tapable.Compiler.runAsChild (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compiler.js:201:7)
    at Object.module.exports.pitch (/Users/tel/tmp/brunchex/node_modules/extract-text-webpack-plugin/loader.js:81:18)
```

**Comment by vhiroki** [comment]
+1

**Comment by Axure** [comment]
Same problem without `webpack-dev-server` (simply `webpack --config wepback.config.js`)

**Comment by VadimKh** [comment]
I solved this problem when install webpack-dev-server locally.

**Comment by claudiut** [comment]
Upgrading the global ```webpack``` package to the latest version (1.12.9) fixed this issue for me. (I had this issue when running ```webpack --config ./wepback.config.js```).

So guys, try a ```npm i -g webpack```.

**Comment by tel** [comment]
Ok, I agree that this resolves this issue.
