### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dongweiming** [webpack/extract-text-webpack-plugin#141]
> NODE_ENV=production webpack --config webpack.config.prod.js

TypeError: Cannot read property 'length' of undefined
    at RawSource.Source.size (/Users/dongweiming/movie2015/node_modules/webpack-core/lib/Source.js:15:22)
    at /Users/dongweiming/movie2015/node_modules/webpack/lib/Stats.js:157:37
    at Array.map (native)
    at Stats.toJson (/Users/dongweiming/movie2015/node_modules/webpack/lib/Stats.js:154:48)
    at Compiler.<anonymous> (/Users/dongweiming/movie2015/node_modules/html-webpack-plugin/index.js:17:51)
    at Compiler.applyPluginsAsync (/Users/dongweiming/movie2015/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/Users/dongweiming/movie2015/node_modules/webpack/lib/Compiler.js:226:7)
    at Compiler.<anonymous> (/Users/dongweiming/movie2015/node_modules/webpack/lib/Compiler.js:184:10)
    at /Users/dongweiming/movie2015/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/dongweiming/movie2015/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/dongweiming/movie2015/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/dongweiming/movie2015/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/dongweiming/movie2015/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/dongweiming/movie2015/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/Users/dongweiming/movie2015/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/dongweiming/movie2015/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/Users/dongweiming/movie2015/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/dongweiming/movie2015/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:137:4)
    at Compilation.applyPluginsAsync (/Users/dongweiming/movie2015/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/dongweiming/movie2015/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/Users/dongweiming/movie2015/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/dongweiming/movie2015/node_modules/extract-text-webpack-plugin/index.js:309:4)
    at Compilation.applyPluginsAsync (/Users/dongweiming/movie2015/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/dongweiming/movie2015/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/Users/dongweiming/movie2015/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/dongweiming/movie2015/node_modules/extract-text-webpack-plugin/index.js:285:5)
    at /Users/dongweiming/movie2015/node_modules/async/lib/async.js:52:16
    at done (/Users/dongweiming/movie2015/node_modules/async/lib/async.js:246:17)
    at /Users/dongweiming/movie2015/node_modules/async/lib/async.js:44:16
    at /Users/dongweiming/movie2015/node_modules/extract-text-webpack-plugin/index.js:269:6

My package.json dependencies is :

```
"devDependencies": {
    "babel-core": "^6.3.15",
    "babel-eslint": "^5.0.0-beta4",
    "babel-loader": "^6.2.0",
    "babel-plugin-react-transform": "^2.0.0-beta1",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "blueimp-tmpl": "^3.1.0",
    "css-loader": "^0.23.0",
    "eslint": "^1.10.3",
    "eslint-plugin-babel": "^3.0.0",
    "eslint-plugin-react": "^3.11.3",
    "express": "^4.13.3",
    "extract-text-webpack-plugin": "^0.9.1",
    "file-loader": "^0.8.5",
    "fontmin": "^0.8.1",
    "html-webpack-plugin": "^1.7.0",
    "image-webpack-loader": "^1.6.2",
    "node-sass": "^3.4.2",
    "postcss-loader": "^0.8.0",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.0.1",
    "rimraf": "^2.4.3",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.9",
    "webpack-dev-middleware": "^1.4.0",
    "webpack-hot-middleware": "^2.6.0"
  },
  "dependencies": {
    "browser-jsonp": "^1.1.2",
    "closest": "0.0.1",
    "jquery-param": "^0.2.0",
    "jump.js": "^0.3.1",
    "merge": "^1.2.0",
    "query-string": "^3.0.0",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-tap-event-plugin": "^0.2.1",
    "sass-pattern": "^0.1.10",
    "scream": "^2.1.0",
    "string-format": "^0.5.0",
    "throttleit": "^1.0.0",
    "wechat.js": "git+https://github.com/sofish/wechat.js.git",
    "whatwg-fetch": "^0.10.1",
    "withinviewport": "^1.0.0"
  }
```

**Comment by omerts** [comment]
how did you solve the above?
