### ISSUE TITLE
Only one CSS from entry point is bundled

### ISSUE THREAD

**Issue by olegkalyta** [webpack/extract-text-webpack-plugin#150]
I have a bunch of plain *.css files and want to combine them in 1 file & then minimize.
when i use style&css loader, i am getting expected result inside *.js file: 
```javascript
loader: 'style!css?minimize'
```

When i use ExtractTextPlugin, i am getting result css from only 1 entry point
```javascript
'use strict';

var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var staticPath = './public';

var extractCSS = new ExtractTextPlugin("./css/[name].css", {allChunks: true});

function cssPath(file) {
  return path.join(__dirname, './client/css', file);
}

var config = {
  entry: {
    customCss: [
      cssPath('app.css'),
      cssPath('file2.css'),
      cssPath('xyz.css'),
      cssPath('sharing.css')
    ],
  },

  output: {
    filename: '/js/[name].js',
    path: path.join(__dirname, staticPath)
  },
  module: {
    loaders: [
      {test: /\.css$/,
        loader: extractCSS.extract('style-loader', 'css-loader')},
        //loader: 'style!css?minimize'}
    ]
  },

  devtool: 'source-map',
  plugins: [
     extractCSS
  ]
};

module.exports = config;
```

In resulting css i have only content of 1 file:

```javascript
file2.css
```

Info: webpack: 1.12.2, 
extract-text-webpack-plugin: 1.0.1

**Comment by olegkalyta** [comment]
Found the reason for it in console log - some files are not bundling because of error

```java-script
ERROR in ./client/css/file2.css
Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve directory '.' in C:\Coding\client\css
    at Compilation.<anonymous> (C:\Coding\node_modules\webpack\lib\Compilation.js:228:38)
    at NormalModuleFactory.onDoneResolving (C:\Coding\node_modules\webpack\lib\NormalModuleFactory.js:28:20)
    at NormalModuleFactory.<anonymous> (C:\Coding\node_modules\webpack\lib\NormalModuleFactory.js:83:20)
...
```

Seems another loaders think this file is OK. May i get more precisely place for error in this file?
