### ISSUE TITLE
SASS loader & ExtractTextPlugin 2.0.0: Cannot read property 'node_modules/extract-text-webpack-plugin' of null

### ISSUE THREAD

**Issue by niieani** [webpack/extract-text-webpack-plugin#211]
After upgrading to webpack-2.1.0-beta.17 and extract-text-webpack-plugin 2.0.0-beta, I get the following error when trying to use **sass-loader** together with **ExtractTextPlugin**:

```js
node_modules/webpack/lib/Compilation.js:457
		rebuilding.forEach(function(cb) {
             ^
TypeError: Cannot read property 'node_modules/extract-text-webpack-plugin' of null
    at node_modules/extract-text-webpack-plugin/index.js:230:27
    at node_modules/webpack/lib/Compilation.js:458:4
    at Array.forEach (native)
    at callback (node_modules/webpack/lib/Compilation.js:457:14)
    at Compilation.<anonymous> (node_modules/webpack/lib/Compilation.js:478:4)
    at node_modules/webpack/lib/Compilation.js:325:10
    at node_modules/webpack/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (node_modules/webpack/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (node_modules/webpack/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (node_modules/webpack/lib/Compilation.js:194:8)
    at Compilation.processModuleDependencies (node_modules/webpack/lib/Compilation.js:179:7)
    at Compilation.<anonymous> (node_modules/webpack/lib/Compilation.js:465:8)
    at node_modules/webpack/lib/Compilation.js:126:4
    at Array.forEach (native)
    at callback (node_modules/webpack/lib/Compilation.js:125:12)
    at node_modules/webpack/lib/Compilation.js:149:10
```

**Comment by niieani** [comment]
Fixed in https://github.com/webpack/extract-text-webpack-plugin/commit/d40c13115f1d591558cbe4837b570642356cc178
