### ISSUE TITLE
CSS modules being imported by `require './styles'` is weird

### ISSUE THREAD

**Issue by shouvik** [webpack/extract-text-webpack-plugin#270]
I am using `extract-text-webpack-plugin` in prod mode to put the styles in a single css file and load it on client. This file gets created just fine, but the import statement of the styles goes for a toss.

I logged what I am getting on the client side for the `import style from './style.css'` satement, and I get this weird object, which has the following structure.

```
Array[1]
  0: Array[4]
i: (t,n)
length: 1
locals: Object // -> this contains the object which I should actually be getting  {headerTitle:"_1VPCU"}
toString: ()__proto__: Array[0]
```

Below is the webpack.config.js file I am using in production mode.

```
var rucksack = require('rucksack-css')
var webpack = require('webpack')
var path = require('path')
var values = require('postcss-modules-values');
var assets = require('postcss-assets');
var CleanPlugin = require('clean-webpack-plugin');
var strip = require('strip-loader');

var projectRootPath = path.resolve(__dirname, '../');
var assetsPath = path.resolve(projectRootPath, './static');


// https://github.com/halt-hammerzeit/webpack-isomorphic-tools
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var WebpackIsomorphicToolsPlugin = require('webpack-isomorphic-tools/plugin');
var webpackIsomorphicToolsPlugin = new WebpackIsomorphicToolsPlugin(require('./webpack-isomorphic-tools'));


const isDevelopment = false;

module.exports = {
  context: path.resolve(__dirname, '..'),
  entry: {
    jsx: './client/index.js',
    html: './client/index.html',
    vendor: [
      'react',
      'react-dom',
      'react-redux',
      'react-router',
      'react-router-redux',
      'redux'
    ]
  },
  output: {
    path: assetsPath,
    filename: 'bundle.js',
  },
  module: {
    loaders: [
      {
        test: /\.html$/,
        loader: 'file?name=[name].[ext]'
      },
      {
        test: /.(png|woff(2)?|eot|ttf|svg)(\?[a-z0-9=\.]+)?$/,
        loader: 'url-loader?limit=100000'
      },
        {
          test: /\.css$/,
          include: /client/,
          loaders: (
            () => {
              if (isDevelopment) {
              return [
                'style-loader',
                'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[local]___[hash:base64:5]',
                'postcss-loader'
              ] } else return [
                ExtractTextPlugin.extract('style-loader'),
                'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[hash:base64:5]',
                'postcss-loader'
              ]
            }
        )()
      },
      {
        test: /\.css$/,
        exclude: /client/,
        loader: 'style!css'
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loaders: (
          () => {
            if (isDevelopment) {
             return ['react-hot','babel-loader']
            } else {
              return [strip.loader('debug'), 'babel-loader']
            }
          }
        )()
      }
    ],
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  postcss: [
    values,
    assets({
      basePath : 'client/assets',
      loadPaths: ['images','fonts'],
      relative : true,
      cacheBuster: true
    }),
    rucksack({
      autoprefixer: true
    })
  ],
  plugins: (() => {
    const plugins = [];

    if(isDevelopment) {
      plugins.push(
        new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
        new webpack.DefinePlugin({
          'process.env': { 
            NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'development') 
          },
          __CLIENT__: true,
          __SERVER__: false,
          __DEVELOPMENT__: true,
          __DEVTOOLS__: true
        }),
        webpackIsomorphicToolsPlugin.development()
      )
    } else {
      plugins.push(
        new CleanPlugin([assetsPath], { root: projectRootPath }),
        new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
        new ExtractTextPlugin('[name]-[chunkhash].css', {allChunks: true}),
        new webpack.DefinePlugin({
          'process.env': { 
            NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'development') 
          },
          __CLIENT__: true,
          __SERVER__: false,
          __DEVELOPMENT__: false,
          __DEVTOOLS__: false
        }),
        new webpack.optimize.UglifyJsPlugin({
          compress: {
            warnings: false
          }
        }),
        //new webpack.optimize.DedupePlugin(),
        //new webpack.optimize.OccurenceOrderPlugin(),
        webpackIsomorphicToolsPlugin
      )
    }
    return plugins
  })(),
  devServer: {
    contentBase: '../client',
    hot: true
  }
}
```

**Comment by Kovensky** [comment]
That is the object as generated by `css-loader`, which `style-loader` or `ExtractTextPlugin.extract` convert into the css modules export. Your invocation of `ExtractTextPlugin.extract` is incorrect; you're giving a string argument instead of an object with `loader` and `fallbackLoader` keys.

**Comment by shouvik** [comment]
As suggested by @Kovensky I used the following configurations:

```

ExtractTextPlugin.extract({
                  fallbackLoader: 'style-loader',
                  loader: 'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[hash:base64:5]!postcss-loader'
                })


```

this leads my build process to throw errors for all the css files. Here is a the stack trace of just one of the files.

```
 ERROR in ./client/components/Tab/style.css
    Module parse failed: /Users/shouvik/Documents/react-project/client/components/Tab/style.css Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (1:0)
        at Parser.pp$4.raise (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
        at Parser.pp.unexpected (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
        at Parser.pp$3.parseExprSubscripts (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
        at Parser.pp$3.parseMaybeUnary (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
        at Parser.pp$3.parseExpression (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
        at Parser.pp$1.parseStatement (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
        at Parser.parse (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
        at Object.parse (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
        at Parser.parse (/Users/shouvik/Documents/react-project/node_modules/webpack/lib/Parser.js:902:15)
        at DependenciesBlock.<anonymous> (/Users/shouvik/Documents/react-project/node_modules/webpack/lib/NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (/Users/shouvik/Documents/react-project/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
        at nextLoader (/Users/shouvik/Documents/react-project/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
        at /Users/shouvik/Documents/react-project/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
        at Storage.finished (/Users/shouvik/Documents/react-project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
        at /Users/shouvik/Documents/react-project/node_modules/graceful-fs/graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

```

**Comment by shouvik** [comment]
Since I am on webpack-1, the api is different as [per the documentation](https://github.com/webpack/extract-text-webpack-plugin/blob/webpack-1/README.md).

Therefore, I reverted my code to 

`ExtractTextPlugin.extract('style-loader','css-loader?modules&sourceMap&importLoaders=1&localIdentName=[hash:base64:5]!postcss-loader')`

now the issue is different. Get the following error:

```
ERROR in ./client/styles/mixins.css
Module build failed: ModuleParseError: Module parse failed: /Users/shouvik/Documents/react-project/client/styles/mixins.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp$4.raise (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/shouvik/Documents/react-project/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/shouvik/Documents/react-project/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/shouvik/Documents/react-project/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/shouvik/Documents/react-project/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/shouvik/Documents/react-project/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/shouvik/Documents/react-project/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/shouvik/Documents/react-project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/shouvik/Documents/react-project/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
    at DependenciesBlock.<anonymous> (/Users/shouvik/Documents/react-project/node_modules/webpack/lib/NormalModule.js:113:20)
    at DependenciesBlock.onModuleBuild (/Users/shouvik/Documents/react-project/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/shouvik/Documents/react-project/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/shouvik/Documents/react-project/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/shouvik/Documents/react-project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/shouvik/Documents/react-project/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./client/containers/AccountBalance/RecentTransactions.js 41:14-48
```

**Comment by shouvik** [comment]
Okay I resolved this issue. Apparently with webpack, the loaders expects an array set, but since this was a single loader being supplied in the array, it wasn't working as intended. 

I updated the config in the following way, as it works 

```

{
          test: /\.css$/,
          include: /client/,
          loader: (
            () => {
              if (isDevelopment) {
              return 'style-loader!css-loader?modules&sourceMap&importLoaders=1&localIdentName=[local]___[hash:base64:5]!postcss-loader'
             } else return ExtractTextPlugin.extract('style-loader','css-loader?modules&sourceMap&importLoaders=1&localIdentName=[hash:base64:5]!postcss-loader')
            }
        )()
      },

```

**Comment by aris-b** [comment]
I had a similar issue, when using `allChunks: true` it worked just fine. But, when i set `allChunks: true`, my style object look like the same as shouvik's. What I did, was just putting the fallbackLoader in an array like this: `fallbackLoader: ['style-loader']` instead of `fallbackLoader: 'style-loader'`
