### ISSUE TITLE
"Cannot find module" with version 2.0.0-beta.4

### ISSUE THREAD

**Issue by EliasJorgensen** [webpack/extract-text-webpack-plugin#274]
Hi, i have an issue when trying to run my production config, using extract-text-webpack-plugin@2.0.0-beta.4 and webpack@2.1.0-beta.25.

I'm getting the following error:

```
ERROR in ./src/Home/index.css
Module build failed: Error: Cannot find module '/home/elias/Projects/Entake/acuity/client/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!style-loader!css-loader'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (/home/elias/Projects/Entake/acuity/client/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/elias/Projects/Entake/acuity/client/node_modules/loader-runner/lib/LoaderRunner.js:164:2)
    at runLoaders (/home/elias/Projects/Entake/acuity/client/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/home/elias/Projects/Entake/acuity/client/node_modules/webpack/lib/NormalModule.js:131:2)
    at NormalModule.build (/home/elias/Projects/Entake/acuity/client/node_modules/webpack/lib/NormalModule.js:179:15)
    at Compilation.buildModule (/home/elias/Projects/Entake/acuity/client/node_modules/webpack/lib/Compilation.js:127:9)
    at /home/elias/Projects/Entake/acuity/client/node_modules/webpack/lib/Compilation.js:306:10
    at /home/elias/Projects/Entake/acuity/client/node_modules/webpack/lib/NormalModuleFactory.js:74:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/elias/Projects/Entake/acuity/client/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/home/elias/Projects/Entake/acuity/client/node_modules/webpack/lib/NormalModuleFactory.js:49:11)
    at onDoneResolving (/home/elias/Projects/Entake/acuity/client/node_modules/webpack/lib/NormalModuleFactory.js:165:6)
    at /home/elias/Projects/Entake/acuity/client/node_modules/webpack/lib/NormalModuleFactory.js:161:6
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:726:13
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:52:16
    at done (/home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:246:17)
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:44:16
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:723:17
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:167:37
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:52:16
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:361:13
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:52:16
    at done (/home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:246:17)
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:44:16
    at /home/elias/Projects/Entake/acuity/client/node_modules/async/lib/async.js:358:17
    at /home/elias/Projects/Entake/acuity/client/node_modules/webpack/lib/NormalModuleFactory.js:217:11
    at onResolved (/home/elias/Projects/Entake/acuity/client/node_modules/enhanced-resolve/lib/Resolver.js:72:10)
 @ ./src/Home/index.js 10:0-21
 @ ./src/App/index.js
 @ ./src/index.js
```

This is my webpack production config:

``` javascript
const Path = require('path')
const Config = require('./config')
const Webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CopyWebpackPlugin = require('copy-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const PATHS = {
  src: Path.join(__dirname, 'src'),
  public: Path.join(__dirname, 'public')
}

module.exports = {

  devtool: 'cheap-module-source-map',

  entry: './src/index.js',

  output: {
    path: PATHS.public,
    publicPath: '/public/',
    filename: 'app.bundle.js'
  },

  target: 'web',

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [{
          loader: 'babel',
          options: {
            presets: [
              ['es2015', { 'modules': false }],
              'stage-1',
              'react',
              'react-optimize'
            ],
            plugins: [
              'react-hot-loader/babel',
              'react-html-attrs',
              'transform-runtime',
              'transform-class-properties',
              'transform-decorators-legacy'
            ]
          }
        }]
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: ExtractTextPlugin.extract({
              fallbackLoader: 'style-loader',
              loader: 'css-loader'
            })
          }
        ]
      }
    ]
  },

  resolve: {
    modules: ['node_modules', 'src'],
    extensions: ['.js', '.css']
  },

  plugins: [
    new Webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('production')
    }),
    new Webpack.ProvidePlugin({
      'Promise': 'es6-promise',
      'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
    }),
    new Webpack.LoaderOptionsPlugin({
      minimize: true
    }),
    new Webpack.NoErrorsPlugin(),
    new HtmlWebpackPlugin({
      inject: false,
      template: 'src/index.ejs',
      css: true,
      title: Config.html.title,
      description: Config.html.description,
      themeColor: Config.html.themeColor
    }),
    new ExtractTextPlugin({ filename: 'styles.css', allChunks: true }),
    new CopyWebpackPlugin([
      { from: `${PATHS.src}/assets`, to: 'assets' }
    ])
  ]
}
```

My CSS works perfectly fine in my development setup. I'm not using CSS modules, and am importing my css files with `import './index.css'`. Do you have any idea what's going wrong?

**Comment by EliasJorgensen** [comment]
For people having the same issue, see #275 for a workaround, until the developers working hard on this project have resolved the issue!

**Comment by bertho-zero** [comment]
:+1:

**Comment by tmair** [comment]
This seems to be the same issue as https://github.com/webpack/extract-text-webpack-plugin/issues/265

**Comment by bebraw** [comment]
Closing in favor of #265.
