### ISSUE TITLE
Error: Chunk.entry was removed. Use hasRuntime()

### ISSUE THREAD

**Issue by kareem3d** [webpack/extract-text-webpack-plugin#283]
I get this error when using last version of webpack `"webpack": "2.1.0-beta.25"`

my webpack configuration
```
 loaders: [
    {
      test: /\.css$/,
      exclude: /node_modules/,
      loader: ExtractTextPlugin.extract(
        'style-loader',
        'css-loader?modules&importLoaders=1!postcss-loader'
      ),
    }
  ]
  plugins: [
    new ExtractTextPlugin('[name].[contenthash].css')
  ]
```

```
Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.Object.defineProperty.get (/home/kareem/goodsense/marketplace/node_modules/webpack/lib/Chunk.js:34:9)
    at /home/kareem/goodsense/marketplace/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/home/kareem/goodsense/marketplace/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins (/home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/tapable/lib/Tapable.js:25:14)
    at Compilation.seal (/home/kareem/goodsense/marketplace/node_modules/webpack/lib/Compilation.js:542:7)
    at Compiler.<anonymous> (/home/kareem/goodsense/marketplace/node_modules/webpack/lib/Compiler.js:468:16)
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (/home/kareem/goodsense/marketplace/node_modules/webpack/lib/Compilation.js:452:10)
    at /home/kareem/goodsense/marketplace/node_modules/webpack/lib/Compilation.js:423:12
    at /home/kareem/goodsense/marketplace/node_modules/webpack/lib/Compilation.js:335:10
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/kareem/goodsense/marketplace/node_modules/webpack/lib/Compilation.js:335:10
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/kareem/goodsense/marketplace/node_modules/webpack/lib/Compilation.js:335:10
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/kareem/goodsense/marketplace/node_modules/webpack/lib/Compilation.js:335:10
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/kareem/goodsense/marketplace/node_modules/webpack/lib/Compilation.js:335:10
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/kareem/goodsense/marketplace/node_modules/webpack/node_modules/async/lib/async.js:44:16
```

**Comment by lexder** [comment]
Try using 2.0.0-beta.3 if you are using 2.0.0-beta.4 (we had the same issue and this fixed it). If even after that the bundle fails, try calling extract with an object containing a "fallbackLoader" and a "loader" property and assign them the property values you're passing now. Good luck!

**Comment by galensheen** [comment]
I have the same issue, can not fixed by using 2.0.0-beta.3. Do you have any method else?

**Comment by RolfVeinoeSorensen** [comment]
I got mine to work. It turned out the 1.x version was being loaded.

From package.json
`  "devDependencies": {
    "@types/node": "^6.0.52",
    "angular2-template-loader": "^0.6.0",
    "awesome-typescript-loader": "^2.2.4",
    "clean-webpack-plugin": "^0.1.14",
    "concurrently": "^3.1.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "^2.0.0-beta.4",
    "file-loader": "^0.9.0",
    "html-webpack-plugin": "^2.25.0",
    "jquery": "^3.1.1",
    "json-loader": "^0.5.4",
    "node-sass": "^4.1.1",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "sass-loader": "^4.1.1",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.0",
    "to-string-loader": "^1.1.5",
    "ts-helpers": "^1.1.1",
    "typescript": "2.0.3",
    "url-loader": "^0.5.6",
    "webpack": "^2.2.0-rc.1",
    "webpack-dev-server": "^1.16.2"
  }`

in my webpack
`            {
                test: /\.scss$/,
                exclude: /node_modules/,
                loader: [
                            ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: ['css-loader'] }),
                            'to-string-loader',
                            'css-loader',
                            'sass-loader'
                        ],
            },`

**Comment by ickyrr** [comment]
+1
@RolfVeinoeSorensen thank you. I had the exact same problem.
