### ISSUE TITLE
Use array of loaders on Webpack 2

### ISSUE THREAD

**Issue by pburtchaell** [webpack/extract-text-webpack-plugin#322]
**webpack**: `2.2.0-rc.1`
**extract-text-webpack-plugin**:  `2.0.0-beta.4`

---

Currently, I am using this format for **`loader`**.

```js
// webpack.config.js
module: {
  rules: [
    {
      test: /\.css?$/,
      loader: ExtractTextPlugin.extract({
        fallbackLoader: 'style-loader',
        loader: 'css-loader?modules&importLoaders-1&camelCase!postcss-loader?sourceMap-inline'
      }
  ]
}
```

However, if I use **`loaders`** and an array (which I prefer to use for config because it is more plain), this throws an error.

```js
// webpack.config.js
module: {
  rules: [{
    test: /\.css?$/,
    loader: ExtractTextPlugin.extract({
      fallbackLoader: 'style-loader',
      loaders: [{
        loader: 'css-loader',
        options: {
          modules: true,
          camelCase: true,
          importLoaders: 1
        }
      }, {
        loader: 'postcss-loader',
        options: {
          sourceMap: 'inline'
        }
    }]
  }]
}
```

This is the error thrown:

```
/Users/pburtchaell/.../node_modules/extract-text-webpack-plugin/index.js:134
	if(!loader.query) return loader.loader;
	          ^

TypeError: Cannot read property 'query' of undefined
    at getLoaderWithQuery (/Users/pburtchaell/.../node_modules/extract-text-webpack-plugin/index.js:134:12)
    at Array.map (native)
    at Function.ExtractTextPlugin.extract (/Users/pburtchaell/.../node_modules/extract-text-webpack-plugin/index.js:201:4)
    at Object.<anonymous> (/Users/pburtchaell/.../webpack.config.js:126:35)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at requireConfig
```

**Comment by kvinogradov** [comment]
@pburtchaell Instead of using key **loaders** in your config use key **loader**.
There is no option **loaders** in ExtractTextPlugin.

**Comment by vichajser** [comment]
I ran into the same problem, but when I was using `loader,` the problem still existed.
my `webpack: 2.2.1`
`node: v8.2.1`
`npm: 5.3.0`
and `extract-text-webpack-plugin: 2.0.0-beta.4`
@kvinogradov  I need you help
