### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by shengnian** [webpack/extract-text-webpack-plugin#344]
```
TypeError: Cannot read property 'replace' of undefined
    at MainTemplate.replacePathVariables (../node_modules/webpack/lib/TemplatedPathPlugin.js:67:3)
    at MainTemplate.applyPluginsWaterfall (../node_modules/tapable/lib/Tapable.js:91:24)
    at Compilation.getPath (../node_modules/webpack/lib/Compilation.js:1082:28)
    at ExtractTextPlugin.<anonymous> (../node_modules/extract-text-webpack-plugin/index.js:307:29)
    at Array.forEach (native)
    at ExtractTextPlugin.<anonymous> (../node_modules/extract-text-webpack-plugin/index.js:296:20)
    at Compilation.applyPluginsAsyncSeries (../node_modules/tapable/lib/Tapable.js:142:13)
    at sealPart2 (../node_modules/webpack/lib/Compilation.js:597:9)
    at next (../node_modules/tapable/lib/Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (../node_modules/extract-text-webpack-plugin/index.js:292:5)
    at ../node_modules/async/dist/async.js:356:16
    at iteratorCallback (../node_modules/async/dist/async.js:936:13)
    at ../node_modules/async/dist/async.js:840:16
    at ../node_modules/extract-text-webpack-plugin/index.js:276:6
    at ../node_modules/async/dist/async.js:356:16
    at iteratorCallback (../node_modules/async/dist/async.js:936:13)
```
```
webpackConfig.module.rules.push[
{ 
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract({
      fallbackLoader: 'style-loader',
      loader: 'css-loader?importLoaders=1&sourceMap&-minimize!postcss-loader!sass-loader'
    })
},
{ 
  test: /\.css$/,
  loader: ExtractTextPlugin.extract({
      fallbackLoader: 'style-loader',
      loader: 'css-loader?importLoaders=1&sourceMap&-minimize!postcss-loader'
    })
}]

webpackConfig.plugins.push(
      new ExtractTextPlugin({
        fileName: '[name].[contenthash].css',
        allChunks: true
      })
  )
```

"webpack": "2.2.0",
"extract-text-webpack-plugin": "2.0.0-beta.5",
"css-loader": "^0.26.1",
"postcss-loader": "^1.2.2",
"sass-loader": "^4.1.1",

**Comment by bebraw** [comment]
Can you provide a small standalone example that's possible to run? I don't see anything obviously wrong in your configuration.

**Comment by samkelleher** [comment]
@shengnian   You are using the property `fileName`, this is a misspelling, it's `filename`. All lower case, not camel case.

This will work:

```
 new ExtractTextPlugin({
        filename: '[name].[contenthash].css',
        allChunks: true
      })
```

**Comment by bebraw** [comment]
@samkelleher Good catch. I marked this as an enhancement as the plugin should do stricter validation to avoid hard crashes.

**Comment by shengnian** [comment]
@samkelleher @bebraw  thanks,  samkelleher's correctly, change the `fileName` to `filename` solved that, thanks agin.

**Comment by kumaresan-subramani** [comment]
**hi,
i also have same  error,**

TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (D:\hence\angular2-webpack-seed\node_modules\@syncfusion\ej2-build\src\utils\common.js:19:42)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\hence\angular2-webpack-seed\node_modules\@syncfusion\ej2-build\src\tasks\aspcore.js:4:47)
    at Module._compile (module.js:643:30)
**but i named correctly 

> finename

**
