### ISSUE TITLE
Getting error on recommended config

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/extract-text-webpack-plugin#64]
This error:

```
TypeError: undefined is not a function
    at Tapable.replacePathVariables (/Users/Ingwie/Work/BIRD3/node_modules/webpack/lib/TemplatedPathPlugin.js:66:4)
    at Tapable.applyPlugins [as applyPluginsWaterfall] (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/tapable/lib/Tapable.js:37:47)
    at Tapable.Compilation.getPath (/Users/Ingwie/Work/BIRD3/node_modules/webpack/lib/Compilation.js:819:27)
    at ExtractTextPlugin.<anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/extract-text-webpack-plugin/index.js:218:29)
    at Array.forEach (native)
    at ExtractTextPlugin.<anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/extract-text-webpack-plugin/index.js:198:20)
    at Tapable.applyPluginsAsync (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/webpack/lib/Compilation.js:537:8)
    at Tapable.next (/Users/Ingwie/Work/BIRD3/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/extract-text-webpack-plugin/index.js:193:5)
````

appears, when I am using the configuration given on the README. What could be possible causes for this?

**Comment by IngwiePhoenix** [comment]
Updating to the latest version fixed this.
