### ISSUE TITLE
"The callback was already called" error when using dev sever

### ISSUE THREAD

**Issue by fongandrew** [webpack/extract-text-webpack-plugin#88]
When using webpack-dev-server, I'm running into an exception on rebuild (but not the initial build) when using ExtractTextPlugin.

Here's the relevant portion of my config:
```
module: {
  loaders: [
    {  test: /\.ts$/, 
       loader: 'awesome-typescript-loader?compiler=ntypescript&module=common&jsx=preserve' },
    {  test: /\.tsx$/, 
       loader: 'babel-loader!awesome-typescript-loader?compiler=ntypescript&module=common&jsx=react' },
    {  test: /\.scss$/,
       loader: ExtractTextPlugin.extract("style-loader", "css?sourceMap!sass?sourceMap") },
    {  test: /\.css$/,
       loader: ExtractTextPlugin.extract("style-loader", "css?sourceMap") }
},

plugins: [
  new ExtractTextPlugin("bundle.css", {allChunks: true})
]
```

And here's the traceback:
```
c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:143
                                throw new Error("callback(): The callback was already called.");
                                
Error: callback(): The callback was already called.
    at context.callback (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:143:11)
    at Object.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\extract-text-webpack-plugin\loader.js:115:6)
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compiler.js:213:10)
    at c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compiler.js:401:12
    at Tapable.next (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\tapable\lib\Tapable.js:67:11)
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\awesome-typescript-loader\dist\index.js:203:13)
    at Tapable.next (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\tapable\lib\Tapable.js:69:14)
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\CachePlugin.js:40:4)
    at Tapable.applyPluginsAsync (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\tapable\lib\Tapable.js:71:13)
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compiler.js:398:9)
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compilation.js:569:13)
    at Tapable.applyPluginsAsync (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compilation.js:564:10)
    at Tapable.applyPluginsAsync (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compilation.js:559:9)
    at Tapable.applyPluginsAsync (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compilation.js:555:8)
    at Tapable.applyPluginsAsync (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
    at Tapable.seal (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compilation.js:517:7)
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compiler.js:395:15)
    at c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\node_modules\tapable\lib\Tapable.js:103:11
    at Tapable.<anonymous> (c:\cygwin64\home\Andrew\ts-flux-boilerplate\node_modules\webpack\lib\Compilation.js:438:10)
```

This error also appears on initial compile if I exclude `allChunks: true` from the plugin options. The error does not appear if I only use `ExtractTextPlugin.extract` on just the .css loader config object or just the .scss loader config object.

My guess is that the reason for the error is that I'm calling `ExtractTextPlugin.extract` twice.  This works as expected during an initial build but chokes on the dev server. I tried creating two separate ExtractTextPlugin instances with different names and tried calling their individual extract methods but I got the same error. Any suggestions?

**Comment by fongandrew** [comment]
Actually, this error seems to only occur when used in connection with sass-loader. Might it be related to https://github.com/webpack/less-loader/issues/18?

**Comment by fongandrew** [comment]
Fixed in https://github.com/s-panferov/awesome-typescript-loader/issues/36.
