### ISSUE TITLE
throwing an error if I turn off sourcemap in uglify js plugin

### ISSUE THREAD

**Issue by deezahyn** [webpack/extract-text-webpack-plugin#98]
Hi, I get an error if I turn off source map in 

```javascript
new webpack.optimize.UglifyJsPlugin({
    compress: {
        warnings: false
    }
    , sourceMap: false
  })
```

I'm trying to disable source map since my build takes 5 minutes long.  Removing it yields 1 minute 40 seconds.

Here's part of my stack trace
```javascript
ERROR in bundle.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/var/www/project/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-map-consumer.js:24:21)
    at /var/www/project/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:62:23
    at Array.forEach (native)
    at Tapable.<anonymous> (/var/www/project/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
    at Tapable.next (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Tapable.<anonymous> (/var/www/project/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:136:4)
    at Tapable.applyPluginsAsync (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/var/www/project/node_modules/webpack/lib/Compilation.js:564:9)
    at Tapable.next (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/var/www/project/node_modules/extract-text-webpack-plugin/index.js:303:4)
    at Tapable.applyPluginsAsync (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.<anonymous> (/var/www/project/node_modules/webpack/lib/Compilation.js:560:8)
    at Tapable.next (/var/www/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/var/www/project/node_modules/extract-text-webpack-plugin/index.js:279:5)
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:52:16
    at done (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:248:21)
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:44:16
    at /var/www/project/node_modules/extract-text-webpack-plugin/index.js:270:6
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:52:16
    at done (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:248:21)
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:44:16
    at /var/www/project/node_modules/extract-text-webpack-plugin/index.js:267:13
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:187:20
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:239:13
    at _arrayEach (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:91:13)
    at _each (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:215:22)
    at /var/www/project/node_modules/extract-text-webpack-plugin/index.js:241:11
    at /var/www/project/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:187:20
```

**Comment by deezahyn** [comment]
moving this issue to webpack:
https://github.com/webpack/webpack/issues/1385
